import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import load_config
from src.data.filters import detect_language, detect_framework, quality_reject, filter_file

CFG = load_config().data

REACT = "import React, { useState } from 'react';\n" + "\n".join(
    f"export function Comp{i}() {{ const [v, setV] = useState({i}); return <div>{{v}}</div>; }}" for i in range(6)
)
FASTAPI = "from fastapi import FastAPI\napp = FastAPI()\n\n" + "\n".join(
    f"@app.get('/r{i}')\nasync def r{i}():\n    return {{'id': {i}}}\n" for i in range(6)
)


def test_detect_language():
    assert detect_language("src/App.tsx") == "tsx"
    assert detect_language("a/b/x.JS") == "js"
    assert detect_language("main.py") == "py"
    assert detect_language("style.css") is None
    assert detect_language("x.d.ts") == "ts"


def test_detect_framework():
    assert detect_framework(REACT, "tsx") == "react"
    assert detect_framework(FASTAPI, "py") == "fastapi"
    assert detect_framework("print('hola')\n" * 30, "py") is None
    assert detect_framework("import { Controller } from '@nestjs/common';", "ts") == "nestjs"
    assert detect_framework("const app = express();", "js") == "express"
    assert detect_framework("from flask import Flask", "py") == "flask"
    assert detect_framework("import Link from 'next/link'", "tsx") == "nextjs"


def test_size_boundaries():
    body = "import React from 'react';\n"
    ok = body + "a" * (CFG.min_bytes - len(body))
    assert len(ok.encode()) == CFG.min_bytes
    assert quality_reject(ok, CFG) != "too_small"
    assert quality_reject(ok[:-1], CFG) == "too_small"
    assert quality_reject("x\n" * (CFG.max_bytes // 2 + 1), CFG) == "too_large"


def test_minified_rejected():
    minified = "var a=function(){return 1};" * 300
    assert quality_reject(minified, CFG) in ("long_lines", "low_alnum")


def test_low_alnum_rejected():
    assert quality_reject("{}[];\n" * 100, CFG) == "low_alnum"


def test_autogenerated_rejected():
    code = "// Code generated by protoc-gen-go. DO NOT EDIT.\n" + REACT
    assert quality_reject(code, CFG) == "autogenerated"
    assert quality_reject("/* eslint-disable */\n// @generated\n" + REACT, CFG) == "autogenerated"


def test_bad_paths_rejected():
    assert filter_file(REACT, "node_modules/x/index.js", CFG)[0] is None
    assert filter_file(REACT, "dist/bundle.js", CFG)[0] is None
    assert filter_file(REACT, "package-lock.json", CFG)[0] is None
    assert filter_file(REACT, "app/x.min.js", CFG)[0] is None


def test_filter_file_accepts_and_labels():
    lang, fw, reason = filter_file(REACT, "src/App.tsx", CFG)
    assert (lang, fw, reason) == ("tsx", "react", None)
    lang, fw, reason = filter_file(FASTAPI, "app/main.py", CFG)
    assert (lang, fw, reason) == ("py", "fastapi", None)


def test_filter_file_rejects_off_domain_and_language():
    generic = "def add(a, b):\n    return a + b\n" * 20
    assert filter_file(generic, "m.py", CFG) == (None, None, "off_domain")
    assert filter_file(REACT, "a.css", CFG) == (None, None, "language")
