"""Filtros en cascada del corpus Full Stack: lenguaje -> ruta -> dominio -> calidad.

Todo son funciones puras. `filter_file` devuelve el motivo de rechazo para poder
medir cuanto descarta cada etapa.
"""

from __future__ import annotations

import re

from src.config import DataConfig

EXT_TO_LANG = {".js": "js", ".jsx": "jsx", ".ts": "ts", ".tsx": "tsx", ".py": "py"}

# Orden = prioridad: el primer framework que coincide etiqueta el archivo.
FRAMEWORK_SIGNATURES = {
    "nestjs": (re.compile(r"@nestjs/|@Controller\(|@Injectable\("), {"js", "jsx", "ts", "tsx"}),
    "nextjs": (re.compile(r"""from\s+['"]next/|['"]next/(link|image|router|navigation)['"]"""), {"js", "jsx", "ts", "tsx"}),
    "react": (re.compile(r"import\s+React\b|from\s+['\"]react['\"]|\buseState\b|\buseEffect\b"), {"js", "jsx", "ts", "tsx"}),
    "express": (re.compile(r"\bexpress\(\)|require\(['\"]express['\"]\)|from\s+['\"]express['\"]"), {"js", "jsx", "ts", "tsx"}),
    "fastapi": (re.compile(r"from\s+fastapi\b|import\s+fastapi\b"), {"py"}),
    "flask": (re.compile(r"from\s+flask\b|import\s+flask\b"), {"py"}),
    "vue": (re.compile(r"from\s+['\"]vue['\"]|defineComponent|\bcreateApp\(|@vue/"), {"js", "ts"}),
    "angular": (re.compile(r"@angular/|@Component\(|@NgModule\("), {"ts"}),
    "django": (re.compile(r"from\s+django\b|import\s+django\b"), {"py"}),
    "pydantic": (re.compile(r"from\s+pydantic\b|from\s+sqlalchemy\b|import\s+sqlalchemy\b|from\s+starlette\b"), {"py"}),
    "python-http": (re.compile(r"^\s*(import|from)\s+(requests|aiohttp|httpx|uvicorn|gunicorn|celery)\b", re.M), {"py"}),
    "python-async": (re.compile(r"\basync\s+def\b|^@app\.", re.M), {"py"}),
    # Dominio ampliado (etiquetas de menor prioridad): JS/TS moderno de aplicacion/servidor.
    "node": (re.compile(r"require\(['\"](fs|http|https|path|os|crypto|dotenv|mongoose|cors|axios|pg|prisma)['\"]\)"
                        r"|from\s+['\"](node:|fs|http|path|axios|mongoose|prisma|@prisma/|typeorm|zod|dotenv|cors)"
                        r"|\bprocess\.env\b|\bmodule\.exports\b|\brouter\.(get|post|put|delete)\("), {"js", "jsx", "ts", "tsx"}),
    "ts-app": (re.compile(r"^\s*(export\s+)?(interface|type)\s+\w+|\bawait\s+fetch\(|\bfetch\(['\"`]", re.M), {"ts", "tsx"}),
}

BAD_PATH = re.compile(
    r"(^|/)(node_modules|dist|build|out|vendor|\.next|coverage|__pycache__|site-packages|bower_components)/"
    r"|(^|/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml)$"
    r"|\.min\.(js|css)$|\.bundle\.js$|\.chunk\.js$",
    re.I,
)

AUTOGENERATED = re.compile(
    r"(auto[- ]?generated|code generated|generated by|do not edit|@generated|this file was generated)",
    re.I,
)


def detect_language(path: str) -> str | None:
    lower = path.lower()
    dot = lower.rfind(".")
    return EXT_TO_LANG.get(lower[dot:]) if dot != -1 else None


def detect_framework(code: str, lang: str) -> str | None:
    for name, (pattern, langs) in FRAMEWORK_SIGNATURES.items():
        if lang in langs and pattern.search(code):
            return name
    return None


def quality_reject(code: str, cfg: DataConfig) -> str | None:
    """Motivo de rechazo por calidad, o None si el archivo es aceptable."""
    size = len(code.encode("utf-8", errors="ignore"))
    if size < cfg.min_bytes:
        return "too_small"
    if size > cfg.max_bytes:
        return "too_large"
    if AUTOGENERATED.search(code[:1000]):
        return "autogenerated"
    if sum(c.isalnum() for c in code) / len(code) <= cfg.min_alnum_ratio:
        return "low_alnum"
    if len(code) / (code.count("\n") + 1) >= cfg.max_mean_line_length:
        return "long_lines"
    return None


def filter_file(code: str, path: str, cfg: DataConfig):
    """Devuelve (lang, framework, None) si pasa, o (None, None, motivo) si no."""
    lang = detect_language(path)
    if lang is None or lang not in cfg.languages:
        return None, None, "language"
    if BAD_PATH.search(path.replace("\\", "/")):
        return None, None, "bad_path"
    framework = detect_framework(code, lang)
    if framework is None:
        return None, None, "off_domain"
    reason = quality_reject(code, cfg)
    if reason:
        return None, None, reason
    return lang, framework, None


# ---------------------------------------------------------------------------
# Fase 9: limpieza determinista (reglas fijadas antes de medir cuanto descartan)
# ---------------------------------------------------------------------------

JS_LANGS = {"js", "jsx", "ts", "tsx"}
_EJS = re.compile(r"<%[=\-_#]?.*?%>", re.S)
_HANDLEBARS = re.compile(r"\{\{\s*[#/>!]")
_PY2_PRINT = re.compile(r"^[ \t]*print[ \t]+(?![(=\s])\S", re.M)
_PY2_EXCEPT = re.compile(r"^[ \t]*except[ \t]+[\w.]+[ \t]*,[ \t]*\w+[ \t]*:", re.M)
_PY2_RAISE = re.compile(r"^[ \t]*raise[ \t]+\w+[ \t]*,", re.M)
_LICENSE_WORDS = re.compile(r"copyright|licen[sc]e|spdx|warranty|permission|all rights reserved", re.I)
_PREFIX_LINE = re.compile(r"""^(#!|#\s*-\*-|#\s*(vim|coding)[:=]|\s*['"]use (client|strict|server)['"];?\s*$)""", re.I)
MIN_LICENSE_LINES = 4
# StarCoderData antepone metadatos al codigo: <reponame>o/r<filename>ruta<gh_stars>n + salto de linea.
_META_HEAD = re.compile(r"\A(?:<reponame>[^\n<]*)?(?:<filename>[^\n<]*)?(?:<gh_stars>[^\n<]*)?\n?")
_META_ANY = re.compile(r"<(?:reponame|filename|gh_stars|issue_start|jupyter_start|commit_before)>")
_B64_RUN = re.compile(r"[A-Za-z0-9+/=]{200,}")
_B64_LINE = re.compile(r"^[ 	]*[A-Za-z0-9+/=]{40,}[ 	]*$", re.M)
MIN_BLOB_LINES = 8
MIN_MOJIBAKE = 3


def _alnum(s: str) -> int:
    return sum(c.isalnum() for c in s)


def _is_blob(code: str) -> bool:
    """Base64/hex/certificados: una racha larga o muchas lineas de relleno alfanumerico.
    Los separadores de comentarios (////, ====) no cuentan: exigen mayoria de alfanumericos."""
    if any(_alnum(m.group(0)) >= 150 for m in _B64_RUN.finditer(code)):
        return True
    return sum(_alnum(l) >= 30 for l in _B64_LINE.findall(code)) >= MIN_BLOB_LINES


def strip_metadata_tags(code: str) -> str:
    """Quita las etiquetas de metadatos que StarCoderData pone al inicio de cada archivo."""
    m = _META_HEAD.match(code)
    return code[m.end():] if m and m.group(0).startswith("<") else code


def clean_reject(code: str, path: str, lang: str) -> str | None:
    """Motivo de rechazo por ruido conocido del corpus, o None. Reglas deterministas."""
    if path.replace("\\", "/").lower().endswith(".d.ts"):
        return "dts"
    if _META_ANY.search(code):
        return "tags"
    if "sourceMappingURL=data:" in code:
        return "sourcemap"
    if code.count("�") >= MIN_MOJIBAKE:
        return "mojibake"
    if _is_blob(code):
        return "blob"
    if lang in JS_LANGS and (_EJS.search(code) or _HANDLEBARS.search(code)):
        return "template"
    if lang == "py":
        if _PY2_PRINT.search(code) or _PY2_EXCEPT.search(code) or _PY2_RAISE.search(code):
            return "python2"
        import ast
        import warnings
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                ast.parse(code)
        except (SyntaxError, ValueError, RecursionError, MemoryError):
            return "py_syntax"
    return None


def strip_license_header(code: str) -> str:
    """Quita el bloque de comentarios inicial si es una cabecera de licencia (>= 4 lineas)."""
    lines = code.split("\n")
    i = 0
    while i < len(lines) and _PREFIX_LINE.match(lines[i]):
        i += 1
    start = i
    if i >= len(lines):
        return code
    first = lines[i].lstrip()
    if first.startswith("/*"):
        j = i
        while j < len(lines) and "*/" not in lines[j]:
            j += 1
        end = min(j + 1, len(lines))
    elif first.startswith("//") or first.startswith("#"):
        marker = "//" if first.startswith("//") else "#"
        j = i
        while j < len(lines) and lines[j].lstrip().startswith(marker):
            j += 1
        end = j
    else:
        return code
    block = lines[start:end]
    if len(block) < MIN_LICENSE_LINES or not _LICENSE_WORDS.search("\n".join(block)):
        return code
    rest = lines[end:]
    while rest and not rest[0].strip():
        rest.pop(0)
    return "\n".join(lines[:start] + rest)


def clean_document(code: str, path: str, lang: str):
    """(codigo_limpio, None) o (None, motivo). Rechaza el ruido y recorta la licencia."""
    code = strip_metadata_tags(code)
    reason = clean_reject(code, path, lang)
    if reason:
        return None, reason
    return strip_license_header(code), None
