"""Filtros en cascada del corpus Full Stack: lenguaje -> ruta -> dominio -> calidad.

Todo son funciones puras. `filter_file` devuelve el motivo de rechazo para poder
medir cuanto descarta cada etapa.
"""

from __future__ import annotations

import re

from src.config import DataConfig

EXT_TO_LANG = {".js": "js", ".jsx": "jsx", ".ts": "ts", ".tsx": "tsx", ".py": "py"}

# Orden = prioridad: el primer framework que coincide etiqueta el archivo.
FRAMEWORK_SIGNATURES = {
    "nestjs": (re.compile(r"@nestjs/|@Controller\(|@Injectable\("), {"js", "jsx", "ts", "tsx"}),
    "nextjs": (re.compile(r"""from\s+['"]next/|['"]next/(link|image|router|navigation)['"]"""), {"js", "jsx", "ts", "tsx"}),
    "react": (re.compile(r"import\s+React\b|from\s+['\"]react['\"]|\buseState\b|\buseEffect\b"), {"js", "jsx", "ts", "tsx"}),
    "express": (re.compile(r"\bexpress\(\)|require\(['\"]express['\"]\)|from\s+['\"]express['\"]"), {"js", "jsx", "ts", "tsx"}),
    "fastapi": (re.compile(r"from\s+fastapi\b|import\s+fastapi\b"), {"py"}),
    "flask": (re.compile(r"from\s+flask\b|import\s+flask\b"), {"py"}),
    "vue": (re.compile(r"from\s+['\"]vue['\"]|defineComponent|\bcreateApp\(|@vue/"), {"js", "ts"}),
    "angular": (re.compile(r"@angular/|@Component\(|@NgModule\("), {"ts"}),
    "django": (re.compile(r"from\s+django\b|import\s+django\b"), {"py"}),
    "pydantic": (re.compile(r"from\s+pydantic\b|from\s+sqlalchemy\b|import\s+sqlalchemy\b|from\s+starlette\b"), {"py"}),
    "python-http": (re.compile(r"^\s*(import|from)\s+(requests|aiohttp|httpx|uvicorn|gunicorn|celery)\b", re.M), {"py"}),
    "python-async": (re.compile(r"\basync\s+def\b|^@app\.", re.M), {"py"}),
    # Dominio ampliado (etiquetas de menor prioridad): JS/TS moderno de aplicacion/servidor.
    "node": (re.compile(r"require\(['\"](fs|http|https|path|os|crypto|dotenv|mongoose|cors|axios|pg|prisma)['\"]\)"
                        r"|from\s+['\"](node:|fs|http|path|axios|mongoose|prisma|@prisma/|typeorm|zod|dotenv|cors)"
                        r"|\bprocess\.env\b|\bmodule\.exports\b|\brouter\.(get|post|put|delete)\("), {"js", "jsx", "ts", "tsx"}),
    "ts-app": (re.compile(r"^\s*(export\s+)?(interface|type)\s+\w+|\bawait\s+fetch\(|\bfetch\(['\"`]", re.M), {"ts", "tsx"}),
}

BAD_PATH = re.compile(
    r"(^|/)(node_modules|dist|build|out|vendor|\.next|coverage|__pycache__|site-packages|bower_components)/"
    r"|(^|/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml)$"
    r"|\.min\.(js|css)$|\.bundle\.js$|\.chunk\.js$",
    re.I,
)

AUTOGENERATED = re.compile(
    r"(auto[- ]?generated|code generated|generated by|do not edit|@generated|this file was generated)",
    re.I,
)


def detect_language(path: str) -> str | None:
    lower = path.lower()
    dot = lower.rfind(".")
    return EXT_TO_LANG.get(lower[dot:]) if dot != -1 else None


def detect_framework(code: str, lang: str) -> str | None:
    for name, (pattern, langs) in FRAMEWORK_SIGNATURES.items():
        if lang in langs and pattern.search(code):
            return name
    return None


def quality_reject(code: str, cfg: DataConfig) -> str | None:
    """Motivo de rechazo por calidad, o None si el archivo es aceptable."""
    size = len(code.encode("utf-8", errors="ignore"))
    if size < cfg.min_bytes:
        return "too_small"
    if size > cfg.max_bytes:
        return "too_large"
    if AUTOGENERATED.search(code[:1000]):
        return "autogenerated"
    if sum(c.isalnum() for c in code) / len(code) <= cfg.min_alnum_ratio:
        return "low_alnum"
    if len(code) / (code.count("\n") + 1) >= cfg.max_mean_line_length:
        return "long_lines"
    return None


def filter_file(code: str, path: str, cfg: DataConfig):
    """Devuelve (lang, framework, None) si pasa, o (None, None, motivo) si no."""
    lang = detect_language(path)
    if lang is None or lang not in cfg.languages:
        return None, None, "language"
    if BAD_PATH.search(path.replace("\\", "/")):
        return None, None, "bad_path"
    framework = detect_framework(code, lang)
    if framework is None:
        return None, None, "off_domain"
    reason = quality_reject(code, cfg)
    if reason:
        return None, None, reason
    return lang, framework, None
